---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.1
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

platforms:
  - name: ubuntu
    driver:
      box: bento/ubuntu-14.04
      #Please use ubuntu-14.04, nD apps will work only on 14.04
      customize:
        memory: 8000
        cpus: 2

suites:
  - name: default
    run_list:
      - recipe[nd-compute::configure]
    attributes:
